services:
  wls:
    container_name: wls
    image: yogendra/yb-workload-simu-app
    environment:
      - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SERVERNAME=yugabytedb-1.local
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -f http://wls.local:8080
      start_interval: 5s
      interval: 2s
      timeout: 1s
      retries: 30
    depends_on:
      yugabytedb-1:
        condition: service_healthy
      yugabytedb-2:
        condition: service_healthy
      yugabytedb-3:
        condition: service_healthy
  yugabytedb-1:
    container_name: yugabytedb-1
    hostname: yugabytedb-1.local
    image: yogendra/yugabyte:2.19.3.0-b140
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --advertise_address=yugabytedb-1.local --cloud_location=cloud.region.zone1 --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "15433:15433"
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-1.local
      start_interval: 5s
      interval: 2s
      timeout: 1s
      retries: 30
  yugabytedb-2:
    container_name: yugabytedb-2
    hostname: yugabytedb-2.local
    image: yogendra/yugabyte:2.19.3.0-b140
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --advertise_address=yugabytedb-2.local --cloud_location=cloud.region.zone2 --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false --join=yugabytedb-1.local
  # bin/yugabyted configure data_placement --constraint_value=cloud.region.zone1,cloud.region.zone2,cloud.region.zone3 --fault_tolerance=zone --rf=3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7001:7000"
      - "9001:9000"
      - "5434:5433"
    depends_on:
      yugabytedb-1:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-2.local
      start_interval: 5s
      interval: 2s
      timeout: 1s
      retries: 30
  yugabytedb-3:
    container_name: yugabytedb-3
    hostname: yugabytedb-3.local
    image: yogendra/yugabyte:2.19.3.0-b140
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --advertise_address=yugabytedb-3.local --cloud_location=cloud.region.zone3 --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false --join=yugabytedb-1.local
  # bin/yugabyted configure data_placement --constraint_value=cloud.region.zone1,cloud.region.zone2,cloud.region.zone3 --fault_tolerance=zone --rf=3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7002:7000"
      - "9002:9000"
      - "5435:5433"
    depends_on:
      yugabytedb-2:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-3.local
      start_interval: 5s
      interval: 2s
      timeout: 1s
      retries: 30
  sqlpad:
    # To use Dockerfile at root of this project, use build instead of image
    # build: ../../
    image: sqlpad/sqlpad:6.11.2
    hostname: "sqlpad"
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: "admin"
      SQLPAD_ADMIN_PASSWORD: "passw0rd"
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__yugabytedb__name: YugabtyeDB
      SQLPAD_CONNECTIONS__yugabytedb__driver: postgres
      SQLPAD_CONNECTIONS__yugabytedb__host: yugabytedb-1
      SQLPAD_CONNECTIONS__yugabytedb__database: yugabyte
      SQLPAD_CONNECTIONS__yugabytedb__username: yugabyte
      SQLPAD_CONNECTIONS__yugabytedb__password: ''
      SQLPAD_CONNECTIONS__yugabytedb__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__yugabytedb__idleTimeoutSeconds: 86400




