version: "3.8"

name: yb-demo
services:
  wls:
    image: yogendra/yb-workload-simu-app
    environment:
      - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SERVERNAME=yugabytedb-1.local
      - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_TOPOLOGYKEYS=cloud.region.*
      - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PORTNUMBER=5433
      - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_DATABASENAME=demo
      - SPRING_DATASOURCE_HIKARI_USERNAME=demo
      - SPRING_DATASOURCE_HIKARI_PASSWORD=demo
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://wls.local:8080
      start_interval: 5s
      interval: 2s
      timeout: 1s
      retries: 30
    depends_on:
      yugabytedb-1:
        condition: service_healthy
      yugabytedb-2:
        condition: service_healthy
      yugabytedb-3:
        condition: service_healthy
  yugabytedb-1:
    hostname: yugabytedb-1.local
    image: yogendra/yugabyte:2.20.0.0-b76
    command:
    - sh
    - -c
    - |
      bin/yugabyted start \
        --advertise_address=yugabytedb-1.local \
        --cloud_location=cloud.region.zone1 \
        --fault_tolerance=zone \
        --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" \
        --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" \
        --daemon=false
    restart: unless-stopped
    volumes:
      - yugabytedb-1:/root/var
    cap_add:
      - NET_ADMIN
    environment:
      - YSQL_DATABASE=demo
      - YSQL_USER=demo
      - YSQL_PASSWORD=demo
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-1.local
      start_interval: 10s
      interval: 2s
      timeout: 1s
      retries: 30
  yugabytedb-2:
    hostname: yugabytedb-2.local
    image: yogendra/yugabyte:2.20.0.0-b76
    command:
    - sh
    - -c
    - |
      bin/yugabyted start \
        --advertise_address=yugabytedb-2.local \
        --cloud_location=cloud.region.zone2 \
        --fault_tolerance=zone \
        --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" \
        --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" \
        --daemon=false \
        --join=yugabytedb-1.local
    restart: unless-stopped
    volumes:
      - yugabytedb-2:/root/var
    cap_add:
      - NET_ADMIN
    environment:
      - YSQL_DATABASE=demo
      - YSQL_USER=demo
      - YSQL_PASSWORD=demo
    depends_on:
      yugabytedb-1:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-2.local
      start_interval: 10s
      interval: 2s
      timeout: 1s
      retries: 30
  yugabytedb-3:
    hostname: yugabytedb-3.local
    image: yogendra/yugabyte:2.20.0.0-b76
    command:
    - sh
    - -c
    - |
      bin/yugabyted start \
        --advertise_address=yugabytedb-3.local \
        --cloud_location=cloud.region.zone3 \
        --fault_tolerance=zone \
        --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" \
        --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" \
        --daemon=false \
        --join=yugabytedb-1.local
    restart: unless-stopped
    volumes:
      - yugabytedb-3:/root/var
    cap_add:
      - NET_ADMIN
    environment:
      - YSQL_DATABASE=demo
      - YSQL_USER=demo
      - YSQL_PASSWORD=demo
    depends_on:
      yugabytedb-1:
        condition: service_healthy
      yugabytedb-2:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=yugabyte postgres/bin/pg_isready -t 1 -p 5433 -U yugabyte -d yugabyte -q -h yugabytedb-3.local
      start_interval: 10s
      interval: 2s
      timeout: 1s
      retries: 30
  db-console:
    hostname: db-console.local
    image: yogendra/yugabyte:2.20.0.0-b76
    restart: unless-stopped
    command: tail -f /dev/null
  sqlpad:
    image: sqlpad/sqlpad:6.11.2
    hostname: sqlpad.local
    ports:
      - "3000:3000"
    depends_on:
      db-lb:
        condition: service_healthy
    environment:
      SQLPAD_ADMIN: "demo"
      SQLPAD_ADMIN_PASSWORD: "demo"
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_ALLOW_CSV_DOWNLOAD: true
      SQLPAD_CONNECTIONS__yugabyte__name: yugabytedb/yugabyte
      SQLPAD_CONNECTIONS__yugabyte__driver: postgres
      SQLPAD_CONNECTIONS__yugabyte__host: db-lb.local
      SQLPAD_CONNECTIONS__yugabyte__port: 5433
      SQLPAD_CONNECTIONS__yugabyte__database: yugabyte
      SQLPAD_CONNECTIONS__yugabyte__username: yugabyte
      SQLPAD_CONNECTIONS__yugabyte__password: yugabyte
      SQLPAD_CONNECTIONS__yugabyte__multiStatementTransactionEnabled: true
      SQLPAD_CONNECTIONS__yugabyte__idleTimeoutSeconds: 86400
      SQLPAD_CONNECTIONS__demo__name: yugabytedb/demo
      SQLPAD_CONNECTIONS__demo__driver: postgres
      SQLPAD_CONNECTIONS__demo__host: db-lb.local
      SQLPAD_CONNECTIONS__demo__port: 5433
      SQLPAD_CONNECTIONS__demo__database: demo
      SQLPAD_CONNECTIONS__demo__username: yugabyte
      SQLPAD_CONNECTIONS__demo__password: yugabyte
      SQLPAD_CONNECTIONS__demo__multiStatementTransactionEnabled: true
      SQLPAD_CONNECTIONS__demo__idleTimeoutSeconds: 86400
      SQLPAD_CONNECTIONS__pg__name: yugabytedb/pg
      SQLPAD_CONNECTIONS__pg__driver: postgres
      SQLPAD_CONNECTIONS__pg__host: db-lb.local
      SQLPAD_CONNECTIONS__pg__port: 5433
      SQLPAD_CONNECTIONS__pg__database: postgres
      SQLPAD_CONNECTIONS__pg__username: yugabyte
      SQLPAD_CONNECTIONS__pg__password: yugabyte
      SQLPAD_CONNECTIONS__pg__multiStatementTransactionEnabled: true
      SQLPAD_CONNECTIONS__pg__idleTimeoutSeconds: 86400

  db-lb:
    image: nginx:1.25.3
    hostname: db-lb.local
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5433:5433/tcp"
      - "15433:15433/tcp"
      - "7000:7000/tcp"
      - "9000:9000/tcp"
      - "9042:9042/tcp"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://db-lb.local:15433
      start_period: 3s
      interval: 2s
      timeout: 1s
      retries: 10
    depends_on:
      yugabytedb-1:
        condition: service_healthy
      yugabytedb-2:
        condition: service_healthy
      yugabytedb-3:
        condition: service_healthy
  demo-nb:
    image: yogendra/yb-demo-nb
    build:
      context: notebook
    hostname: demo-nb.local
    restart: always
    volumes:
      - ../..:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - NOTEBOOK_ARGS=--PasswordIdentityProvider.hashed_password='argon2:$$argon2id$$v=19$$m=10240,t=10,p=8$$V1fvnM4WG6vgjRELSzVIeQ$$uWX/TQRbEyJ3l3qbyGlIh2kSgKVs0y0dWUk7rV5a4GM'
    ports:
      - "8888:8888/tcp"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://demo-nb.local:8888
      start_period: 3s
      interval: 2s
      timeout: 1s
      retries: 10
    depends_on:
      db-lb:
        condition: service_healthy
  pgadmin4:
    image: dpage/pgadmin4:7
    container_name: pdadmin4
    hostname: pgadmin4.local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@yugabyte.com
      PGADMIN_DEFAULT_PASSWORD: demo
      PGADMIN_LISTEN_PORT: 9080
    volumes:
    - ./pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "9080:9080"
    depends_on:
      db-lb:
        condition: service_healthy
  logs:
    hostname: logs.local
    image: yogendra/yugabyte:2.20.0.0-b76
    volumes:
    - ./logs:/tools:ro
    - yugabytedb-1:/nodes/1:ro
    - yugabytedb-2:/nodes/2:ro
    - yugabytedb-3:/nodes/3:ro
    command: tail -f /dev/null
volumes:
  yugabytedb-1:
  yugabytedb-2:
  yugabytedb-3:

